name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci --audit=false

      - name: Jam variables into files
        run: echo "${{ vars.FIREBASE_CONFIG }}" > src/config.ts

      - name: Build site
        run: npm run build

      - name: Create 404 page
        run: cp ./dist/index.html ./dist/404.html

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
